### ISSUE TITLE
Team up

### ISSUE THREAD

**Issue by ja-martinez** [ASU-CompMethodsPhysics-PHY494/final-march-madness#1]
@bkatterm Hey can I join?

**Comment by bkatterm** [comment]
You are more than welcome to. Sorry I was out today, had some medical
things going on. I will be on campus tomorrow around 1 to meet up with Ian
to learn some object oriented Python stuff, do you want to meet up around
then? In the meantime, I can forward you a few things when I get home on
exactly what we are dealing with concept wise.

Bryan

**Comment by ja-martinez** [comment]
Don't worry! I am actually leaving tomorrow at around 1 because of medical stuff too. We can communicate through here or through email.

Also, I believe we should start adding what we have to the wiki page!

**Comment by ja-martinez** [comment]
@bkatterm Hey Bryan, I have added some info to the wiki, so please read it and tell me what you think, or add anything you might think is missing.

Alejandro

**Comment by orbeckst** [comment]
FYI: This is all _public_ so you might want to be careful with what you post in the issue tracker.

You can edit posts (click on the pen icon) in case you want to remove, e.g. email addresses or any other information.

**Comment by ja-martinez** [comment]
Thank you!
