### ISSUE TITLE
Probability

### ISSUE THREAD

**Issue by ja-martinez** [ASU-CompMethodsPhysics-PHY494/final-march-madness#3]
@bkatterm Hey bryan, I used the probability formula you gave me and it sometimes gives numbers that are not in the range [0, 1]. Sometimes they are negative and sometimes greater than 1. How should we fix this?

**Comment by bkatterm** [comment]
Oh yeah, I saw that too... The denomination should be + not -

**Comment by bkatterm** [comment]
If you are going off what I wrote on the board that is... If you are going
off of what I have in sim_v4, the formula in the code should be correct

**Comment by ja-martinez** [comment]
Nice! The error was that "-" sign!
